name: amazic_ads_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
#  google_mobile_ads:
#    path: packages/google_mobile_ads
  google_mobile_ads: ^5.2.0

  collection: ^1.17.2
  logger: ^2.0.2
  visibility_detector: ^0.4.0+2
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.2
  http: ^1.2.1
  fluttertoast: ^8.2.6
  adjust_sdk: ^4.38.0
  shared_preferences: ^2.3.1
  screenshot: ^3.0.0
  path_provider: ^2.1.4
  advertising_id: ^2.6.0
  in_app_purchase: ^3.2.0
  in_app_purchase_storekit: ^0.3.18+1
  firebase_analytics: ^11.0.0
  firebase_remote_config: ^5.0.0
#  google_mlkit_text_recognition: ^0.14.0
  win32: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.amazic.ad
        pluginClass: AmazicPlugin
      ios:
        pluginClass: AmazicPlugin
